#!/usr/bin/env python3
"""Turn the saved timings sheets into the data file the web page reads.

Reads every timings/<SEASON>_<COMPETITION>_timings.html and writes
docs/data.js, which defines a single global (window.AVAILABILITY_DATA). It's a
plain script rather than JSON on purpose: a <script src> tag works both on
GitHub Pages and when you just double-click docs/index.html locally, whereas
fetch() of a JSON file is blocked on file:// URLs.

Adding a competition means dropping a file in timings/ and re-running this -
the season and competition name come from the filename.

Run by hand, or by the scheduled GitHub Action:

    python build_data.py             # rebuild from the saved files
    python build_data.py --refresh   # re-download the ones with a live URL
"""

from __future__ import annotations

import argparse
import datetime
import json
import os
import sys

import availability as av

HERE = os.path.dirname(os.path.abspath(__file__))
OUTPUT = os.path.join(HERE, "docs", "data.js")

# One character per kickoff column, per team.
FREE, BUSY, BLANK = "G", "R", "-"


def build_competition(competition, sheet):
    days = list(dict.fromkeys(slot.day for slot in sheet.slots))
    entry = {
        "key": competition.key,
        "title": competition.title,
        "season": competition.season,
        "competition": competition.competition,
        "source": competition.url,
        "days": days,
        "slots": [
            {"day": days.index(slot.day), "utc": slot.utc, "est": slot.est, "bst": slot.bst}
            for slot in sheet.slots
        ],
        "teams": [],
    }

    for team in sheet.teams:
        row = "".join(
            FREE if team.availability.get(slot.col) == "free"
            else BUSY if team.availability.get(slot.col) == "busy"
            else BLANK
            for slot in sheet.slots
        )
        entry["teams"].append(
            {"country": team.country, "player": team.player, "slots": row}
        )

    return entry


def build_payload(refresh=False):
    found = av.competitions()
    if not found:
        raise ValueError(
            "no competitions in {}. Save a sheet there as "
            "<SEASON>_<COMPETITION>_timings.html, e.g. S17_WC_timings.html."
            .format(os.path.relpath(av.TIMINGS_DIR, HERE))
        )

    entries = []
    for competition in found:
        # Only competitions with a published URL can be refreshed; the rest are
        # used exactly as saved, which is the point of keeping them in timings/.
        wanted = refresh and competition.url
        source = av.load_sheet(competition, refresh=bool(wanted))
        entries.append(build_competition(competition, av.build_sheet(source)))

    return {
        "generated": datetime.datetime.now(datetime.timezone.utc)
        .replace(microsecond=0)
        .isoformat()
        .replace("+00:00", "Z"),
        # Which one the page opens on. Worked out here so the page and the CLI
        # can't drift apart on what "the current competition" means.
        "default": av.default_competition(found).key,
        "competitions": entries,
    }


def read_existing(path=OUTPUT):
    """Parse the payload out of a previously written data.js, if there is one."""
    try:
        with open(path, encoding="utf-8") as handle:
            text = handle.read()
    except OSError:
        return None
    start = text.find("{")
    end = text.rfind("}")
    if start == -1 or end == -1:
        return None
    try:
        return json.loads(text[start:end + 1])
    except ValueError:
        return None


def unchanged(new, old):
    """True if only the timestamp differs - i.e. nobody's availability moved.

    The scheduled rebuild runs hourly, so without this it would commit a fresh
    timestamp every hour and bury real changes in noise.
    """
    if not old:
        return False
    return {k: v for k, v in new.items() if k != "generated"} == \
           {k: v for k, v in old.items() if k != "generated"}


def write(payload, path=OUTPUT):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    body = json.dumps(payload, indent=1, ensure_ascii=False)
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("// Generated by build_data.py - do not edit by hand.\n")
        handle.write("window.AVAILABILITY_DATA = ")
        handle.write(body)
        handle.write(";\n")
    return path


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--refresh",
        action="store_true",
        help="re-download competitions that have a published sheet URL",
    )
    args = parser.parse_args(argv)

    try:
        payload = build_payload(refresh=args.refresh)
    except (OSError, ValueError) as error:
        print("Could not build the data file: {}".format(error), file=sys.stderr)
        return 1

    if unchanged(payload, read_existing()):
        print("No change - {} left alone.".format(os.path.relpath(OUTPUT, HERE)))
        return 0

    path = write(payload)
    print("Wrote {}:".format(os.path.relpath(path, HERE)))
    for entry in payload["competitions"]:
        submitted = sum(
            1 for t in entry["teams"] if FREE in t["slots"] or BUSY in t["slots"]
        )
        print("  {:<14} {} teams ({} with availability), {} kickoff times, {} days".format(
            entry["key"], len(entry["teams"]), submitted,
            len(entry["slots"]), len(entry["days"]),
        ))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
